### ISSUE TITLE
Small icons seem to be missing

### ISSUE THREAD

**Issue by TheShark27** [hahagu/WindowsThumbnailGenerator#7]
Hi, this software worls flawlessly! However, one of the folders I added the thumbnail to appeared in my file explorer Quick Access menu, and it looks a bit funky.
I think the small icon size should not have thumbnail previews, as they are generally too small to make out the images they contain.

This could be solved by adding the "small" size to the .ico files that are generated. Small icons have a slightly different shape compared to their bigger counterparts: for example, they have more rounded corners, and a more prominent folder handle. The current icons that are generated seem to be missing this size, so Windows just resizes the bigger sizes to a smaller one.

Thank you for this software, it's incredibly useful!

**Comment by hahagu** [comment]
As I've said in issue #4 , if I were to fix this, the program would take double what it already does to generate thumbnails for single folders, since it has to generate two thumbnails for a single folder. I'll see if this is solvable in a more efficient manner, but if it can not be, it might not be implemented.

Also, as an alternative, a static image of a folder containing white files can be implemented without too much performance impact, although that will not show the contents.

**Comment by TheShark27** [comment]
Thanks for the response!

I suggested this because another software I'm using, FolderPainter, already uses .ico files with 8 scaling options. I don't think having 8 icons for each file is necessary, but having at least the smallest size could be nice.

Also, generating a preview for such a small icon would be pointless, as it would be too small to even distinguish the images, so a good implementation would be just adding the default Win11 small folder icon. That's why would still have a relatively low performance impact.

That's just my suggestion, and once again, thanks for being one of those devs that add older Windows features back in Windows!

**Comment by hahagu** [comment]
I will take a look at it!
